### PR TITLE
Fixes #17: remove babel-polyfill

### LINKED ISSUE #17: babel-polyfill reference in `index.js` adds to page weight
I am profiling the page weight of a React application and noticed `core-js` is one of the big offenders:

```
lodash: 724.25 KB (20.2%)
react-dom: 506.86 KB (14.1%)
core-js: 252.96 KB (7.04%)
availity-uikit: 242.81 KB (6.76%)
```

Removing the `babel-polyfill` reference from [src/index.js#L1](https://github.com/Availity/availity-reactstrap-validation/blob/master/src/index.js#L1) removes `core-js` from the final bundle.

```
lodash: 724.25 KB (21.3%)
react-dom: 506.86 KB (14.9%)
availity-uikit: 242.81 KB (7.16%)
```

Thoughts on removing `babel-polyfill`?  What would you recommend?

### PR DESCRIPTION
**Pull request by robmcguinness**
Ran the unit tests and manually checked the examples. Unless I missed something I say we remove the polyfill ⭐️

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Sorta-kinda. This is one of those things where karma really shines; testing in the browser. While you removed babel-polyfill and the tests were able to run successfully, all it really means is that node has a more spec compliant JavaScript engine (V8) than IE.
Things like `Promise` are used, and now a user of this lib will need to bring their own `Promise` polyfill if they plan on supporting IE.  This is fairly common, just need to add something to the README.
There is also apparently [1 use of Array.prototype.includes()](https://github.com/Availity/availity-reactstrap-validation/blob/bcd352d51d0f18eff838336a6a3c00d22803e646/src/AvBaseInput.js#L218) which would need to be changed to `.indexOf > -1` (which is what I used everywhere else. Yay consistency :upside_down_face:)
I'm not too sure about anything else, I just did a quick search for es2015+ prototype methods I find useful to see if I used them here.

**Comment by robmcguinness** [comment]
ah good catch.

**Comment by dmarkic** [comment]
Hello,
is it possible, that by removing polyfill, this part of code is not working anymore as expected:
https://github.com/Availity/availity-reactstrap-validation/blob/master/src/AvBaseInput.js#L161

I see it's translated differently in the distribution now.

Kind regards,
Dejan

**Comment by TheSharpieOne** [comment]
That only needs a polyfil for ie8 and lower. Everything in that line works in ie9+. The array spread gets transformed in the dist. If you need to support ie8, you can include the polyfil yourself.

**Comment by dmarkic** [comment]
Can you check this sandbox: https://codesandbox.io/s/n39vk6mwqp

You simply cannot select a value, it seems to get reset. In your distribution the AvBaseInput.js:161 gets translated to this:
return [].concat(event.target.options).filter(function (_ref) {
var selected = _ref.selected;
return selected;
}).map(function (_ref2) {
var value = _ref2.value;
return value;
});

When I download source and use it in project directly, it gets translated to this:

[].concat((0,d.default)(e.target.options)).filter(function(e){return e.selected}).map(function(e){return e.value})

It's working in this way.

**Comment by TheSharpieOne** [comment]
You hardcoded a value, so that value should not change.
Same thing happens in a select using just react/html without this library.

**Comment by dmarkic** [comment]
AvBaseInput is handling the state, this is just the initial value. You can remove the value={[]} altogether in sandbox and it still doesn't work.

**Comment by dmarkic** [comment]
I've checked it now. You should change the line #161 to this:

let ret = [];
let options = event.target.options;
for(let i = 0; i < options.length; i++){
  if (options[i].selected){
    ret.push(options[i].value);
  }
}
return ret;

It's the safest thing I found to be working in all browsers. It should also solve the issue #41

**Pull request merged**
