### PR TITLE
feat(AvCheckboxGroup): add support for checkbox groups

### PR DESCRIPTION
**Pull request by reeseschultz**

### CODE REVIEW

**Comment by robmcguinness** [comment]
@TheSharpieOne good catch!

**Comment by reeseschultz** [comment]
I will update the aliasing. Also, I'll change the styling so that the enabled inputs are green, and disabled are gray. I'm assuming that is the desired styling.

**Comment by reeseschultz** [comment]
@TheSharpieOne I pushed a couple commits to address the issues you mentioned. When you have time, please take another look and let me know what you think.

**Comment by TheSharpieOne** [comment]
The min and max checked validation also have the style issue. Not sure the best way to handle this as this is where it really starts to get different from radios.
The styles themselves are tied to the DOM's ValidityState. You could use [`.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/setCustomValidity) on the underlying checkbox to control the ValidityState. 
image
image

**Comment by reeseschultz** [comment]
Thanks for your feedback. I'll dig into the code and come up with an appropriate fix.

**Comment by reeseschultz** [comment]
@TheSharpieOne The `.setCustomValidity` function did the trick! Much appreciated.

Also, thanks for bearing with me. I just learned React for the sake of updating this library. Is there anything else you want me to add/change before the merge?

**Pull request merged**
